name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */3 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Random Execute
        run: |
          R=$RANDOM
          M=20000
          echo $R
          if [ $R -lt $M ];then exit 1;fi  

      - name: Auto green
        run: |
          echo 'begining'
          S=$(curl 'https://v1.hitokoto.cn/?c=a&encode=text')
          git config --local user.email "hackful@qq.com"
          git config --local user.name "hackful5281"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "${S}"
          git push
          echo 'end'
